### ISSUE TITLE
box ious

### ISSUE THREAD

**Issue by biggerlambda** [cjnolet/textbox_proposals_fcrn#1]
This is not an issue but a clarification I wanted since I am finishing up writing the same code for torch.  I did not see computations involving box iou in the code. Are they somewhere in the code?

**Comment by cjnolet** [comment]
Are you able to clarify what you mean by box ious? If you mean turning the ground truth bounding boxes into the feature tensor, you can find that [here](https://github.com/cjnolet/textbox_proposals_fcrn/blob/master/build_dataset.py#L137) and [here](https://github.com/cjnolet/textbox_proposals_fcrn/blob/master/build_dataset.py#L152).

**Comment by cjnolet** [comment]
I just realized, I think you are referring to the intersection over union. Lol, I'm not used to seeing it in lower case. I'll get my code for the NMS and IoU out in this repo, likely today.

**Comment by biggerlambda** [comment]
Yes I meant intersection over union. Thanks for letting me know.
